# Generated by Django 2.1.1 on 2018-10-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='fileUpload',
            field=models.FileField(default='', upload_to='uploaded_image/'),
        ),
    ]
