# Generated by Django 2.1.1 on 2018-10-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Category',
            field=models.CharField(default='Tutorials', max_length=200),
        ),
    ]
